### PR TITLE
Handle autologin error

### LINKED ISSUE #154: Auto Login Fails when localstorage name is set to a name you don't own
### Steps to reproduce

- Log into the manager locally on a network.
- Switch networks, (i.e. mainnet to testnet)
- Launch the app locally
- Login fails silently
- Click the login button and the spinner is spinning.

### LINKED ISSUE #176: Automatic login fails when switching wallets
Steps to reproduce:
1. Login with a domain and a wallet
2. Close manager
3. Switch wallet
4. Click in login -> trying to login to previous domain that is not owned

### PR DESCRIPTION
**Pull request by jessgusclark**
Rather than returning null with no autoredirect, return false. However, only change the state of showModal if the result is true.

This allows for autologin to work, and when it fails, it allows the user to click login and use different credentials. 

Finally, on Metamask, we listen for the accountsChanged event and we run start() to get the current account. This listener is not available in Nifty. 

Closes #176 
Closes #154

### CODE REVIEW

File: src/app/auth/operations.js [hunk 1]
```diff
@@ -84,6 +84,8 @@ export const start = callback => (dispatch) => {
       .then(() => callback && callback())
       .catch(e => dispatch(errorEnable(e.message)));
   }
+
+  window.ethereum.on('accountsChanged', () => dispatch(start()));
```
Comment (ilanolkies) [inline src/app/auth/operations.js]: 🙌
