### PR TITLE
USD Conversion API

### LINKED ISSUE #180: Error that is returned by coinmarketcap.com API crashes manager
The response from coinmarketcap.com's API error message returns a string that when sent to the error notification component crashes the browser.

**Steps to reproduce:**

1) get yourself temporarily banned from their API

image

2) site crashes on registration

### PR DESCRIPTION
**Pull request by jessgusclark**
Prevent the manager from failing to load the registration page when it can't access coinmarketcap's API. 

Closes #180

### CODE REVIEW

File: src/app/tabs/registrar/components/RentalPeriodComponent.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ class RentalPeriodComponent extends Component {
             rif
           </p>
           <p className="usdPrice">
-            {!gettingConversionRate && <>{`$${usdAmount} USD`}</> }
+            {(!gettingConversionRate && conversionRate) && <>{`$${usdAmount} USD`}</> }
```
Comment (ilanolkies) [inline src/app/tabs/registrar/components/RentalPeriodComponent.js]: Great
